[package]
name = "rzig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
log = "0.4.14"
regex = "1.10.3"

[[bin]]
name = "rzig"
path = "src/rzig.rs"
